spring:
  application:
    name: k8s-spring-demo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://172.17.0.3:5432/grafana_data_source
    username: postgres
    password: ma3aY03h1!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
